add_test( [==[Tests for `tAllpass` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tAllpass` filer]==]  )
set_tests_properties( [==[Tests for `tAllpass` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tAllpassSO` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tAllpassSO` filer]==]  )
set_tests_properties( [==[Tests for `tAllpassSO` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tThiranAllpassSOCascade` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tThiranAllpassSOCascade` filer]==]  )
set_tests_properties( [==[Tests for `tThiranAllpassSOCascade` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tOnePole` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tOnePole` filer]==]  )
set_tests_properties( [==[Tests for `tOnePole` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tCookOnePole` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tCookOnePole` filer]==]  )
set_tests_properties( [==[Tests for `tCookOnePole` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tTwoPole` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tTwoPole` filer]==]  )
set_tests_properties( [==[Tests for `tTwoPole` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tOneZero` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tOneZero` filer]==]  )
set_tests_properties( [==[Tests for `tOneZero` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tTwoZero` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tTwoZero` filer]==]  )
set_tests_properties( [==[Tests for `tTwoZero` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tPoleZero` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tPoleZero` filer]==]  )
set_tests_properties( [==[Tests for `tPoleZero` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tBiQuad` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tBiQuad` filer]==]  )
set_tests_properties( [==[Tests for `tBiQuad` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tSVF` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tSVF` filer]==]  )
set_tests_properties( [==[Tests for `tSVF` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tEfficientSVF` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tEfficientSVF` filer]==]  )
set_tests_properties( [==[Tests for `tEfficientSVF` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tHighpass` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tHighpass` filer]==]  )
set_tests_properties( [==[Tests for `tHighpass` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tButterworth` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tButterworth` filer]==]  )
set_tests_properties( [==[Tests for `tButterworth` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tFIR` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tFIR` filer]==]  )
set_tests_properties( [==[Tests for `tFIR` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tVZFilter` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tVZFilter` filer]==]  )
set_tests_properties( [==[Tests for `tVZFilter` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tVZFilterLS` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tVZFilterLS` filer]==]  )
set_tests_properties( [==[Tests for `tVZFilterLS` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tVZFilterHS` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tVZFilterHS` filer]==]  )
set_tests_properties( [==[Tests for `tVZFilterHS` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tVZFilterBell` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tVZFilterBell` filer]==]  )
set_tests_properties( [==[Tests for `tVZFilterBell` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tVZFilterBR` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tVZFilterBR` filer]==]  )
set_tests_properties( [==[Tests for `tVZFilterBR` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tDiodeFilter` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tDiodeFilter` filer]==]  )
set_tests_properties( [==[Tests for `tDiodeFilter` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tLadderFilter` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tLadderFilter` filer]==]  )
set_tests_properties( [==[Tests for `tLadderFilter` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tTiltFilter` filer]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tTiltFilter` filer]==]  )
set_tests_properties( [==[Tests for `tTiltFilter` filer]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tCycle` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tCycle` object]==]  )
set_tests_properties( [==[Tests for `tCycle` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tTriangle` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tTriangle` object]==]  )
set_tests_properties( [==[Tests for `tTriangle` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tSquare` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tSquare` object]==]  )
set_tests_properties( [==[Tests for `tSquare` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tSawtooth` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tSawtooth` object]==]  )
set_tests_properties( [==[Tests for `tSawtooth` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tPBSineTriangle` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tPBSineTriangle` object]==]  )
set_tests_properties( [==[Tests for `tPBSineTriangle` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tPBTriangle` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tPBTriangle` object]==]  )
set_tests_properties( [==[Tests for `tPBTriangle` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tPBPulse` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tPBPulse` object]==]  )
set_tests_properties( [==[Tests for `tPBPulse` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tPBSaw` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tPBSaw` object]==]  )
set_tests_properties( [==[Tests for `tPBSaw` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tPBSawSquare` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tPBSawSquare` object]==]  )
set_tests_properties( [==[Tests for `tPBSawSquare` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tSawOS` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tSawOS` object]==]  )
set_tests_properties( [==[Tests for `tSawOS` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tPhasor` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tPhasor` object]==]  )
set_tests_properties( [==[Tests for `tPhasor` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tNoise` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tNoise` object]==]  )
set_tests_properties( [==[Tests for `tNoise` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tNeuron` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tNeuron` object]==]  )
set_tests_properties( [==[Tests for `tNeuron` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tMBPulse` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tMBPulse` object]==]  )
set_tests_properties( [==[Tests for `tMBPulse` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tMBTriangle` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tMBTriangle` object]==]  )
set_tests_properties( [==[Tests for `tMBTriangle` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tMBSineTri` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tMBSineTri` object]==]  )
set_tests_properties( [==[Tests for `tMBSineTri` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tMBSaw` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tMBSaw` object]==]  )
set_tests_properties( [==[Tests for `tMBSaw` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tMBSawPulse` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tMBSawPulse` object]==]  )
set_tests_properties( [==[Tests for `tMBSawPulse` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tTable` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tTable` object]==]  )
set_tests_properties( [==[Tests for `tTable` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tWaveTable` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tWaveTable` object]==]  )
set_tests_properties( [==[Tests for `tWaveTable` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tWaveOsc` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tWaveOsc` object]==]  )
set_tests_properties( [==[Tests for `tWaveOsc` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tWaveTableS` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tWaveTableS` object]==]  )
set_tests_properties( [==[Tests for `tWaveTableS` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tWaveOscS` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tWaveOscS` object]==]  )
set_tests_properties( [==[Tests for `tWaveOscS` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tIntPhasor` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tIntPhasor` object]==]  )
set_tests_properties( [==[Tests for `tIntPhasor` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tSquareLFO` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tSquareLFO` object]==]  )
set_tests_properties( [==[Tests for `tSquareLFO` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tSawSquareLFO` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tSawSquareLFO` object]==]  )
set_tests_properties( [==[Tests for `tSawSquareLFO` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tTriLFO` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tTriLFO` object]==]  )
set_tests_properties( [==[Tests for `tTriLFO` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Tests for `tSineTriLFO` object]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Tests for `tSineTriLFO` object]==]  )
set_tests_properties( [==[Tests for `tSineTriLFO` object]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
add_test( [==[Test SAD!]==] /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test/tests [==[Test SAD!]==]  )
set_tests_properties( [==[Test SAD!]==] PROPERTIES WORKING_DIRECTORY /Users/josnyder/dev/Electrobass_JUCE/Builds/modules/LEAF/test)
set( tests_TESTS [==[Tests for `tAllpass` filer]==] [==[Tests for `tAllpassSO` filer]==] [==[Tests for `tThiranAllpassSOCascade` filer]==] [==[Tests for `tOnePole` filer]==] [==[Tests for `tCookOnePole` filer]==] [==[Tests for `tTwoPole` filer]==] [==[Tests for `tOneZero` filer]==] [==[Tests for `tTwoZero` filer]==] [==[Tests for `tPoleZero` filer]==] [==[Tests for `tBiQuad` filer]==] [==[Tests for `tSVF` filer]==] [==[Tests for `tEfficientSVF` filer]==] [==[Tests for `tHighpass` filer]==] [==[Tests for `tButterworth` filer]==] [==[Tests for `tFIR` filer]==] [==[Tests for `tVZFilter` filer]==] [==[Tests for `tVZFilterLS` filer]==] [==[Tests for `tVZFilterHS` filer]==] [==[Tests for `tVZFilterBell` filer]==] [==[Tests for `tVZFilterBR` filer]==] [==[Tests for `tDiodeFilter` filer]==] [==[Tests for `tLadderFilter` filer]==] [==[Tests for `tTiltFilter` filer]==] [==[Tests for `tCycle` object]==] [==[Tests for `tTriangle` object]==] [==[Tests for `tSquare` object]==] [==[Tests for `tSawtooth` object]==] [==[Tests for `tPBSineTriangle` object]==] [==[Tests for `tPBTriangle` object]==] [==[Tests for `tPBPulse` object]==] [==[Tests for `tPBSaw` object]==] [==[Tests for `tPBSawSquare` object]==] [==[Tests for `tSawOS` object]==] [==[Tests for `tPhasor` object]==] [==[Tests for `tNoise` object]==] [==[Tests for `tNeuron` object]==] [==[Tests for `tMBPulse` object]==] [==[Tests for `tMBTriangle` object]==] [==[Tests for `tMBSineTri` object]==] [==[Tests for `tMBSaw` object]==] [==[Tests for `tMBSawPulse` object]==] [==[Tests for `tTable` object]==] [==[Tests for `tWaveTable` object]==] [==[Tests for `tWaveOsc` object]==] [==[Tests for `tWaveTableS` object]==] [==[Tests for `tWaveOscS` object]==] [==[Tests for `tIntPhasor` object]==] [==[Tests for `tSquareLFO` object]==] [==[Tests for `tSawSquareLFO` object]==] [==[Tests for `tTriLFO` object]==] [==[Tests for `tSineTriLFO` object]==] [==[Test SAD!]==])
